### ISSUE TITLE
__mt_attribution shows on sub path and expiration is 1969-12-31

### ISSUE THREAD

**Issue by kurry421** [yanirclsr/MarTech#4]
HI - __mt_attribution is showing an expiration date of 1969-12-31 23:59:59
additionally It is being stored as a cookie on the sub path (ie not "/", but "/foo")

Any ideas around why? I'm trying this on chrome.

**Comment by yanirclsr** [comment]
Thanks for letting me know.
I fixed the problems you described.
https://github.com/yanirclsr/MarTech/commit/c03207243fbb9ab0f7401061b2e3a68a54b0cc0f
